# Generated by Django 3.0.1 on 2020-01-08 13:48
# Это файл миграции для данных до того, как мы из модели PizzaOrder
# удалим поле address (насколько я поняла)
from django.db import migrations


def forward(apps, shema_editor):
    """
    apps         -
    shema_editor - ne nuzhen
    """
    PizzaOrder = apps.get_model("shop", "PizzaOrder")
    for order in PizzaOrder.objects.all():
        city, street = order.address.split(" ")
        order.city = city
        order.street = street
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200108_1346'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]

